<template>
  <AppLayout>
    <main class="mx-auto w-full max-w-7xl flex-1 px-4 py-10 sm:px-6 lg:px-8">
      <p class="text-sm font-semibold text-[#008060]">Карьерный навигатор</p>
      <h1 class="mt-2 text-3xl font-semibold tracking-tight text-[#202223]">Поймите, где вы сейчас и куда расти дальше</h1>
      <p class="mt-3 max-w-3xl text-[#616161]">Сначала оценим рабочий уровень, затем учтём навыки и выбранное направление. Это займёт несколько минут.</p>

      <div v-if="readonlyReport" class="mt-8"><section class="report"><ReportContent :result="result" :error="error" :career-path="careerPath" :copied="copied" @copy="copyLink" /></section></div>

      <div v-else class="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]">
        <form class="rounded-xl border border-[#e1e3e5] bg-white p-6 shadow-sm" @submit.prevent="submit">
          <div class="steps" aria-label="Этапы создания карьерного плана"><span :class="{ active: step >= 1 }">1. Уровень</span><span :class="{ active: step >= 2 }">2. Навыки</span><span :class="{ active: step >= 3 }">3. Цель</span></div>
          <section v-if="step === 1" class="space-y-6"><div><h2>Определим текущий уровень</h2><p>Отвечайте по реальному опыту работы, а не по названию должности.</p></div><div><label class="label">Есть ли у вас коммерческий опыт в IT?</label><div class="options"><label v-for="item in experienceOptions" :key="item.value" class="option"><input v-model="form.commercial_experience" type="radio" :value="item.value"/><span>{{ item.label }}</span></label></div></div><div v-for="(question, index) in gradeQuestions" :key="question.title" class="question"><b>{{ index + 1 }}. {{ question.title }}</b><div class="mt-3 space-y-2"><label v-for="option in question.options" :key="option.value" class="option"><input v-model="form.grade_answers[index]" type="radio" :value="option.value"/><span>{{ option.text }}</span></label></div></div></section>
          <section v-else-if="step === 2" class="space-y-6"><div><h2>Расскажите о навыках</h2><p>Выберите инструменты, с которыми уже работали. По ним определим сильные стороны и пробелы.</p></div><div><div class="mb-2 flex justify-between"><label class="label">Ваши навыки</label><button v-if="form.skills.length" type="button" class="text-xs text-[#008060]" @click="form.skills = []">Очистить</button></div><input v-model="skillQuery" type="search" class="field" placeholder="Введите навык"/><div v-if="skillQuery" class="skill-results"><button v-for="skill in matchingSkills" :key="skill.id" type="button" class="skill-option" @click="toggleSkill(skill.id)">{{ skill.title }}<span>{{ selected(skill.id) ? 'Убрать' : 'Добавить' }}</span></button></div><div class="mt-3 flex flex-wrap gap-2"><button v-for="skill in selectedSkills" :key="skill.id" type="button" class="tag" @click="toggleSkill(skill.id)">{{ skill.title }} ×</button></div></div><div><label class="label">Направление</label><select v-model="form.group_id" class="field"><option :value="null">Помочь определить</option><option v-for="group in groups" :key="group.id" :value="group.id">{{ group.title }}</option></select></div></section>
          <section v-else class="space-y-6"><div><h2>Выберите цель</h2><p>Цель не меняет ваш текущий уровень - она помогает составить подходящий маршрут развития.</p></div><div><label class="label">Интересующая роль</label><select v-model="form.category_id" class="field"><option :value="null">Предложить подходящую роль</option><option v-for="category in availableCategories" :key="category.id" :value="category.id">{{ category.title }}</option></select></div><div class="summary"><span>Предварительный уровень</span><b>{{ preliminaryLevel }}</b><small>{{ preliminaryText }}</small></div></section>
          <p v-if="formError" class="form-error">{{ formError }}</p><div class="mt-8 flex items-center justify-between gap-3"><button v-if="step > 1" type="button" class="back" @click="step--">Назад</button><span v-else></span><button v-if="step < 3" type="button" class="primary" @click="nextStep">Продолжить</button><button v-else :disabled="loading" class="primary">{{ loading ? 'Формируем…' : 'Построить карьерный план' }}</button></div>
        </form>
        <aside class="rounded-xl border border-[#e1e3e5] bg-[#f7f8f8] p-6"><p class="text-sm font-semibold text-[#008060]">Что вы получите</p><h2 class="mt-2 text-xl font-semibold">Персональный ориентир развития</h2><ul class="mt-5 space-y-4 text-sm text-[#616161]"><li><b>Текущий уровень</b><br/>по опыту и самостоятельности, а не только по навыкам.</li><li><b>Следующий шаг</b><br/>достижимая роль в выбранном направлении.</li><li><b>План развития</b><br/>навыки, которые помогут подготовиться к переходу.</li></ul></aside>
      </div>
      <section v-if="!readonlyReport && result" class="mt-8"><ReportContent :result="result" :error="error" :career-path="careerPath" :copied="copied" @copy="copyLink" /></section>
    </main>
  </AppLayout>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue';
import AppLayout from '@/Layouts/AppLayout.vue';
import ReportContent from '@/Components/RecommendationReport.vue';
const props = defineProps({ skills: Array, groups: Array, categories: Array, qualifications: Array, reportUuid: String });
const step = ref(1), skillQuery = ref(''), result = ref(null), error = ref(''), formError = ref(''), loading = ref(false), copied = ref(false), uuid = ref(props.reportUuid || null);
const form = ref({ commercial_experience: null, grade_answers: [null, null, null, null, null], skills: [], group_id: null, category_id: null });
const readonlyReport = computed(() => Boolean(props.reportUuid || result.value?.report_uuid));
const experienceOptions = [{ value: 'none', label: 'Нет, ищу первую работу или стажировку' }, { value: 'up_to_year', label: 'Да, до 1 года' }, { value: 'one_to_three', label: 'Да, от 1 до 3 лет' }, { value: 'three_plus', label: 'Да, более 3 лет' }];
const gradeQuestions = [
  { title: 'Как вы обычно работаете над задачей?', options: [{ value: 0, text: 'Нужна подробная инструкция и регулярная проверка.' }, { value: 1, text: 'Сам выполняю типовые задачи, сложное согласовываю.' }, { value: 2, text: 'Сам выбираю подход и отвечаю за результат.' }, { value: 3, text: 'Определяю подход для команды и помогаю другим.' }] },
  { title: 'За что вы отвечаете?', options: [{ value: 0, text: 'За небольшой участок работы.' }, { value: 1, text: 'За задачу целиком.' }, { value: 2, text: 'За качество решений в части продукта.' }, { value: 3, text: 'За направление или результат команды.' }] },
  { title: 'Как вы принимаете решения?', options: [{ value: 0, text: 'Работаю по инструкции или готовому примеру.' }, { value: 1, text: 'Ищу решение сам, при необходимости спрашиваю.' }, { value: 2, text: 'Оцениваю варианты, риски и предлагаю решение.' }, { value: 3, text: 'Принимаю решения, влияющие на команду и продукт.' }] },
  { title: 'Как вы взаимодействуете с коллегами?', options: [{ value: 0, text: 'В основном получаю обратную связь от наставника.' }, { value: 1, text: 'Обсуждаю задачи с командой на равных.' }, { value: 2, text: 'Помогаю коллегам и объясняю сложные решения.' }, { value: 3, text: 'Развиваю людей, распределяю работу или нанимаю.' }] },
  { title: 'Как вы влияете на работу команды?', options: [{ value: 0, text: 'Пока осваиваю процессы и инструменты.' }, { value: 1, text: 'Предлагаю улучшения в своих задачах.' }, { value: 2, text: 'Улучшаю подходы и договорённости команды.' }, { value: 3, text: 'Планирую приоритеты и отвечаю за общий результат.' }] },
];
const availableCategories = computed(() => form.value.group_id ? props.categories.filter(item => item.group_id === form.value.group_id) : props.categories);
const selectedSkills = computed(() => props.skills.filter(item => form.value.skills.includes(item.id)));
const matchingSkills = computed(() => props.skills.filter(item => item.title.toLowerCase().includes(skillQuery.value.toLowerCase())).slice(0, 8));
const selected = id => form.value.skills.includes(id);
const toggleSkill = id => { form.value.skills = selected(id) ? form.value.skills.filter(item => item !== id) : [...form.value.skills, id]; skillQuery.value = ''; };
const preliminaryLevel = computed(() => { if (form.value.commercial_experience === 'none') return 'Intern'; const values = form.value.grade_answers.filter(item => item !== null); const avg = values.length ? values.reduce((sum, item) => sum + item, 0) / values.length : 0; return avg < .8 ? 'Junior' : avg < 1.8 ? 'Middle' : avg < 2.7 ? 'Senior' : 'Lead'; });
const preliminaryText = computed(() => form.value.commercial_experience === 'none' ? 'Для первой роли важнее база, практика и завершённые проекты.' : 'Итог определён по вашим ответам о самостоятельности и ответственности.');
const nextStep = () => { formError.value = ''; if (step.value === 1 && (!form.value.commercial_experience || form.value.grade_answers.some(item => item === null))) { formError.value = 'Ответьте на вопрос об опыте и выберите вариант для каждого утверждения.'; return; } if (step.value === 2 && !form.value.skills.length) { formError.value = 'Добавьте хотя бы один навык - так рекомендации будут полезнее.'; return; } step.value++; };
const request = async (url, options = {}) => { const response = await fetch(url, { headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, ...options }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Не удалось сформировать план'); return data; };
const submit = async () => { loading.value = true; error.value = ''; try { const data = await request('/api/recommendations', { method: 'POST', body: JSON.stringify(form.value) }); result.value = data.data; uuid.value = data.data.report_uuid; history.replaceState({}, '', `/recommendations/${uuid.value}`); } catch (exception) { error.value = exception.message; } finally { loading.value = false; } };
const copyLink = async () => { await navigator.clipboard.writeText(result.value.report_url); copied.value = true; setTimeout(() => copied.value = false, 1500); };
const careerPath = computed(() => { const categoryId = result.value?.input_data?.category_id || result.value?.opportunities?.[0]?.category_id; let node = new Map(props.categories.map(item => [item.id, item])).get(categoryId), path = []; while (node) { path.unshift(node); node = props.categories.find(item => item.id === node.parent_id); } return path; });
onMounted(async () => { if (!uuid.value) return; try { const data = await request(`/api/recommendations/${uuid.value}`); result.value = data.data; } catch (exception) { error.value = exception.message; } });
</script>

<style scoped>
.steps{display:flex;gap:.5rem;margin-bottom:2rem;color:#8c9196;font-size:.78rem;font-weight:600}.steps span{border-radius:999px;background:#f1f1f1;padding:.4rem .65rem}.steps .active{background:#d9f1e7;color:#006e52}.label{display:block;margin-bottom:.45rem;font-size:.875rem;font-weight:600}.field{width:100%;border:1px solid #8c9196;border-radius:.375rem;background:#fff;padding:.65rem .75rem;font-size:.875rem}.field:focus{border-color:#008060;outline:2px solid #00806020}.options,.question{display:grid;gap:.55rem}.option{display:flex;gap:.65rem;align-items:flex-start;border:1px solid #e1e3e5;border-radius:.5rem;background:#fff;padding:.7rem .8rem;font-size:.875rem;cursor:pointer}.option:has(input:checked){border-color:#008060;background:#f1f8f5}.question{border-top:1px solid #e1e3e5;padding-top:1.25rem}.question b{font-size:.95rem}.question .option{padding:.55rem .7rem}.skill-results{max-height:13rem;overflow:auto;border:1px solid #d2d5d8;border-radius:.375rem;background:#fff}.skill-option{display:flex;width:100%;justify-content:space-between;padding:.6rem .75rem;text-align:left;font-size:.875rem}.skill-option span{color:#008060;font-size:.75rem}.tag{border-radius:999px;background:#e3f1df;padding:.35rem .65rem;color:#006e52;font-size:.8rem}.summary{border:1px solid #b7d9c8;border-radius:.5rem;background:#f1f8f5;padding:1rem}.summary span,.summary small{display:block;color:#4a4f54;font-size:.8rem}.summary b{display:block;margin:.25rem 0;color:#006e52;font-size:1.2rem}.primary{border-radius:.375rem;background:#008060;padding:.7rem 1rem;color:#fff;font-size:.875rem;font-weight:600}.primary:disabled{opacity:.6}.back{border:1px solid #8c9196;border-radius:.375rem;padding:.65rem .9rem;font-size:.875rem}.form-error{margin-top:1.25rem;border:1px solid #f1b9b5;border-radius:.5rem;background:#fff5f4;padding:.75rem;color:#b42318;font-size:.875rem}.report{max-width:100%}.notice{border:1px solid #f1d59a;border-radius:.5rem;background:#fff8db;padding:1rem;font-size:.875rem;color:#6d5600}.copy{border:1px solid #b18a24;border-radius:.375rem;background:#fff;padding:.4rem .7rem;font-size:.75rem;font-weight:600;white-space:nowrap}.card,.panel{border:1px solid #e1e3e5;border-radius:.75rem;background:#fff;padding:1.25rem;box-shadow:0 1px 2px #0000000d}.card p,.card small,.inner p,.panel li p{color:#6d7175;font-size:.8rem}.card b{display:block;margin:.4rem 0;font-size:1.35rem}.panel{margin-top:1.25rem}.panel h2{font-size:1.1rem;font-weight:600}.inner{border:1px solid #e1e3e5;border-radius:.5rem;padding:1rem}.inner strong{display:block;margin-top:.75rem;color:#008060;font-size:.8rem}
</style>
