<template>
  <AppLayout><main class="mx-auto w-full max-w-6xl flex-1 px-4 py-10">
    <p class="text-sm font-semibold text-[#008060]">Карьерный навигатор</p><h1 class="mt-2 text-3xl font-semibold">Поймите, где вы сейчас и куда расти дальше</h1>
    <div class="mt-8 grid gap-6 lg:grid-cols-[360px_1fr]">
      <form @submit.prevent="submit" class="h-fit rounded-xl border border-[#e1e3e5] bg-white p-6 shadow-sm">
        <div class="space-y-5"><div><div class="mb-2 flex justify-between"><label class="label">Ваши навыки</label><button v-if="form.skills.length" type="button" class="text-xs text-[#008060]" @click="form.skills=[]">Очистить</button></div><input v-model="skillQuery" type="search" class="field" placeholder="Введите навык"/><div v-if="skillQuery" class="skill-results"><button v-for="skill in matchingSkills" :key="skill.id" type="button" class="skill-option" @click="toggleSkill(skill.id)">{{ skill.title }}<span>{{ selected(skill.id)?'Убрать':'Добавить' }}</span></button></div><div class="mt-3 flex flex-wrap gap-2"><button v-for="skill in selectedSkills" :key="skill.id" type="button" class="tag" @click="toggleSkill(skill.id)">{{ skill.title }} ×</button></div></div><div><label class="label">Направление</label><select v-model="form.group_id" class="field"><option :value="null">Помочь определить</option><option v-for="x in groups" :key="x.id" :value="x.id">{{ x.title }}</option></select></div><div><label class="label">Целевая роль</label><select v-model="form.category_id" class="field"><option :value="null">Помочь определить</option><option v-for="x in availableCategories" :key="x.id" :value="x.id">{{ x.title }}</option></select></div><div><label class="label">Текущий уровень</label><select v-model="form.qualification_id" class="field"><option :value="null">Определить по профилю</option><option v-for="x in qualifications" :key="x.id" :value="x.id">{{ x.title }}</option></select></div><button :disabled="loading" class="w-full rounded-md bg-[#008060] px-4 py-3 text-sm font-semibold text-white">{{ loading?'Анализируем…':'Построить карьерный план' }}</button></div>
      </form>
      <section><p v-if="error" class="rounded border border-red-200 bg-red-50 p-4 text-red-800">{{ error }}</p><p v-else-if="!result" class="rounded-xl border border-dashed border-[#c9cccf] bg-white p-10 text-center text-[#6d7175]">Добавьте навыки, чтобы увидеть уровень, доступные роли и план развития.</p><template v-else><div class="notice"><p>После закрытия вкладки введённые данные не сохраняются в браузере. Сохраните ссылку на отчёт.</p><div class="mt-3 flex gap-2"><input readonly :value="result.report_url" class="field min-w-0 flex-1"/><button type="button" class="copy" @click="copyLink">{{ copied?'Скопировано':'Копировать ссылку' }}</button></div></div><div class="mt-5 grid gap-4 sm:grid-cols-3"><article class="card"><p>Текущая точка</p><b>{{ result.profile.current_level }}</b><small>{{ result.profile.basis }}</small></article><article class="card"><p>Навыков в профиле</p><b>{{ result.profile.skills_count }}</b><small>Чем точнее набор, тем точнее маршрут.</small></article><article class="card"><p>Следующий уровень</p><b>{{ result.growth.next_level || 'Верхний уровень' }}</b><small>Ориентир для развития.</small></article></div><article v-if="careerPath.length" class="panel"><h2>Ваш возможный путь</h2><CareerPath :nodes="careerPath" /></article><article class="panel"><h2>Что уже доступно</h2><div class="mt-4 grid gap-3 sm:grid-cols-3"><div v-for="x in result.opportunities" :key="x.title" class="inner"><b>{{ x.title }}</b><p>{{ x.group }}</p><strong>{{ x.fit }}% соответствие профилю</strong></div></div></article><article class="panel"><h2>Что подтянуть</h2><div class="mt-3 flex flex-wrap gap-2"><span v-for="x in result.growth.skills_to_build" :key="x" class="tag">{{ x }}</span></div></article><article class="panel"><h2>План следующего шага</h2><ol class="mt-4 space-y-3"><li v-for="(x,i) in result.roadmap" :key="x.title"><b>{{ i+1 }}. {{ x.title }}</b><p>{{ x.text }}</p></li></ol></article></template></section>
    </div>
  </main></AppLayout>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'; import AppLayout from '@/Layouts/AppLayout.vue'; import CareerPath from '@/Components/CareerPath.vue';
const props=defineProps({skills:Array,groups:Array,categories:Array,qualifications:Array,reportUuid:String});const form=ref({skills:[],group_id:null,category_id:null,qualification_id:null}),skillQuery=ref(''),result=ref(null),error=ref(''),loading=ref(false),copied=ref(false),uuid=ref(props.reportUuid||null);const availableCategories=computed(()=>form.value.group_id?props.categories.filter(x=>x.group_id===form.value.group_id):props.categories);const selectedSkills=computed(()=>props.skills.filter(x=>form.value.skills.includes(x.id)));const matchingSkills=computed(()=>props.skills.filter(x=>x.title.toLowerCase().includes(skillQuery.value.toLowerCase())).slice(0,8));const selected=id=>form.value.skills.includes(id);const toggleSkill=id=>{form.value.skills=selected(id)?form.value.skills.filter(x=>x!==id):[...form.value.skills,id];skillQuery.value=''};const request=async(url,opt={})=>{const r=await fetch(url,{headers:{'Content-Type':'application/json',Accept:'application/json'},...opt});const d=await r.json();if(!r.ok)throw new Error(d.message||'Ошибка анализа');return d};const submit=async()=>{loading.value=true;try{const d=await request(uuid.value?`/api/recommendations/${uuid.value}`:'/api/recommendations',{method:uuid.value?'PUT':'POST',body:JSON.stringify(form.value)});result.value=d.data;uuid.value=d.data.report_uuid;history.replaceState({},'',`/recommendations/${uuid.value}`)}catch(e){error.value=e.message}finally{loading.value=false}};const copyLink=async()=>{await navigator.clipboard.writeText(result.value.report_url);copied.value=true;setTimeout(()=>copied.value=false,1500)};const careerPath=computed(()=>{let node=new Map(props.categories.map(x=>[x.id,x])).get(result.value?.opportunities?.[0]?.category_id),out=[];while(node){out.unshift(node);node=props.categories.find(x=>x.id===node.parent_id)}return out});onMounted(async()=>{if(!uuid.value)return;const d=await request(`/api/recommendations/${uuid.value}`);result.value=d.data;Object.assign(form.value,d.data.input_data)});
</script>
<style scoped>.label{display:block;margin-bottom:.4rem;font-size:.875rem;font-weight:600}.field{width:100%;border:1px solid #8c9196;border-radius:.375rem;background:#fff;padding:.6rem .7rem;font-size:.875rem}.skill-results{max-height:13rem;overflow:auto;border:1px solid #d2d5d8;border-radius:.375rem;background:#fff}.skill-option{display:flex;width:100%;justify-content:space-between;padding:.6rem .75rem;text-align:left;font-size:.875rem}.skill-option span{color:#008060;font-size:.75rem}.tag{border-radius:999px;background:#e3f1df;padding:.35rem .65rem;color:#006e52;font-size:.8rem}.notice{border:1px solid #f1d59a;border-radius:.5rem;background:#fff8db;padding:1rem;font-size:.875rem;color:#6d5600}.copy{border:1px solid #b18a24;border-radius:.375rem;background:#fff;padding:.4rem .7rem;font-size:.75rem;font-weight:600;white-space:nowrap}.card,.panel{border:1px solid #e1e3e5;border-radius:.75rem;background:#fff;padding:1.25rem;box-shadow:0 1px 2px #0000000d}.card p,.card small,.inner p,.panel li p{color:#6d7175;font-size:.8rem}.card b{display:block;margin:.4rem 0;font-size:1.35rem}.panel{margin-top:1.25rem}.panel h2{font-size:1.1rem;font-weight:600}.inner{border:1px solid #e1e3e5;border-radius:.5rem;padding:1rem}.inner strong{display:block;margin-top:.75rem;color:#008060;font-size:.8rem}</style>
