<template>
  <p v-if="error" class="rounded border border-red-200 bg-red-50 p-4 text-red-800">{{ error }}</p>
  <p v-else-if="!result" class="rounded-xl border border-dashed border-[#c9cccf] bg-white p-10 text-center text-[#6d7175]">Загружаем сохранённый отчёт…</p>
  <template v-else>
    <div class="notice"><p>После закрытия вкладки введённые данные не сохраняются в браузере. Сохраните ссылку на готовый отчёт, если захотите вернуться к нему позже.</p><div class="mt-3 flex gap-2"><input readonly :value="result.report_url" class="field min-w-0 flex-1"/><button type="button" class="copy" @click="$emit('copy')">{{ copied ? 'Скопировано' : 'Копировать ссылку' }}</button></div></div>
    <div class="mt-5 grid gap-4 sm:grid-cols-3"><article class="card"><p>Текущий уровень</p><b>{{ result.profile.current_level }}</b><small>{{ result.profile.basis }}</small></article><article class="card"><p>Навыков в профиле</p><b>{{ result.profile.skills_count }}</b><small>Чем точнее набор, тем точнее маршрут.</small></article><article class="card"><p>Следующий уровень</p><b>{{ result.growth.next_level || 'Верхний уровень' }}</b><small>Ориентир для развития.</small></article></div>
    <article v-if="result.assessment" class="panel"><h2>Почему этот уровень</h2><p class="summary-text">{{ result.assessment.summary }}</p><div class="mt-4 grid gap-3 sm:grid-cols-2"><div class="insight insight-good"><b>Уже получается</b><ul><li v-for="item in result.assessment.strengths" :key="item">{{ item }}</li></ul></div><div class="insight"><b>Что усилить</b><ul><li v-for="item in result.assessment.focus" :key="item">{{ item }}</li></ul></div></div></article>
    <article v-if="careerPaths.length" class="panel"><h2>Возможные карьерные пути</h2><p class="summary-text">Основной вариант выбран по числу совпавших навыков и достаточному числу вакансий. Остальные пути - альтернативы.</p><div class="mt-4 grid gap-4" :class="careerPaths.length > 1 ? 'lg:grid-cols-2' : ''"><div v-for="(path, index) in careerPaths" :key="path.group" class="direction"><p class="direction-name">{{ index === 0 ? `Основной вариант: ${path.group}` : `Альтернативный вариант: ${path.group}` }}</p><CareerPath :nodes="path.nodes" /></div></div></article>
    <article v-if="result.directions?.length" class="panel"><h2>Что уже доступно по направлениям</h2><p class="summary-text">В расчёт попадают только роли вашего текущего и следующего уровня, а направления с малой выборкой не показываются.</p><div class="mt-4 grid gap-4"><section v-for="(direction, index) in result.directions" :key="direction.group_id" class="direction"><h3>{{ index === 0 ? `Основной вариант - ${direction.group}` : direction.group }}</h3><p class="mt-1 text-sm text-[#616161]">В анализе {{ direction.sample_size }} вакансий текущего и следующего уровня.</p><div class="mt-4"><p class="subheading">Подходящие роли</p><div class="mt-2 grid gap-3 sm:grid-cols-3"><div v-for="role in direction.roles" :key="role.category_id" class="inner"><b>{{ role.title }}</b><p>{{ role.vacancies_count }} вакансий в выборке</p><strong>{{ role.matched_skills_count }} из {{ role.selected_skills_count }} выбранных навыков встречаются в роли</strong></div></div></div><div class="mt-4"><p class="subheading">Ваши навыки в вакансиях направления</p><div class="mt-2 grid gap-2 sm:grid-cols-2"><div v-for="skill in direction.matched_skills" :key="skill.id" class="skill-gap"><b>{{ skill.title }}</b><span>{{ skill.percent }}% вакансий</span></div></div><p v-if="direction.missing_skills.length" class="mt-2 text-sm text-[#616161]">Не встретились в этой выборке: {{ direction.missing_skills.join(', ') }}.</p></div><div class="mt-4"><p class="subheading">Что подтянуть для {{ result.growth.next_level || 'следующего' }}</p><p class="mt-1 text-sm text-[#616161]">Проценты показывают, как часто навык встречается в вакансиях следующего уровня именно этого направления.</p><div v-if="direction.skills_to_build.length" class="mt-2 grid gap-2 sm:grid-cols-2"><div v-for="skill in direction.skills_to_build" :key="skill.title" class="skill-gap"><b>{{ skill.title }}</b><span>{{ skill.percent }}% вакансий</span></div></div><p v-else class="mt-2 text-sm text-[#616161]">Для этого направления пока недостаточно вакансий следующего уровня, чтобы выделить надёжные дефициты.</p></div></section></div></article>
    <article v-if="result.portfolio_evidence" class="panel"><h2>Что подтвердит ваш уровень</h2><div class="mt-4 grid gap-3 sm:grid-cols-3"><div v-for="(item, index) in result.portfolio_evidence" :key="item.title" class="inner"><div class="evidence-title"><span class="number">{{ index + 1 }}</span><b>{{ item.title }}</b></div><p>{{ item.text }}</p></div></div></article>
    <article class="panel"><h2>{{ result.roadmap_direction ? `План следующего шага: ${result.roadmap_direction}` : 'План следующего шага' }}</h2><p v-if="result.roadmap_direction" class="summary-text">План построен для основного варианта. Для альтернативных направлений ориентируйтесь на навыки в их карточках выше.</p><ol class="mt-4 space-y-3"><li v-for="(item, index) in result.roadmap" :key="item.title"><b>{{ index + 1 }}. {{ item.title }}</b><p>{{ item.text }}</p></li></ol></article>
  </template>
</template>

<script setup>
import CareerPath from '@/Components/CareerPath.vue';

defineProps({ result: Object, error: String, careerPaths: { type: Array, default: () => [] }, copied: Boolean });
defineEmits(['copy']);
</script>

<style scoped>
.field{width:100%;border:1px solid #8c9196;border-radius:.375rem;background:#fff;padding:.65rem .75rem;font-size:.875rem}.notice{border:1px solid #f1d59a;border-radius:.5rem;background:#fff8db;padding:1rem;font-size:.875rem;color:#6d5600}.copy{border:1px solid #b18a24;border-radius:.375rem;background:#fff;padding:.4rem .7rem;font-size:.75rem;font-weight:600;white-space:nowrap}.card,.panel{border:1px solid #e1e3e5;border-radius:.75rem;background:#fff;padding:1.25rem;box-shadow:0 1px 2px #0000000d}.card p,.card small,.inner p,.panel li p{color:#6d7175;font-size:.8rem}.card b{display:block;margin:.4rem 0;font-size:1.35rem}.panel{margin-top:1.25rem}.panel h2{font-size:1.1rem;font-weight:600}.panel h3{font-size:1rem;font-weight:600}.inner{border:1px solid #e1e3e5;border-radius:.5rem;background:#fff;padding:1rem}.inner strong{display:block;margin-top:.75rem;color:#008060;font-size:.8rem}.direction{border:1px solid #dfe3e0;border-radius:.65rem;background:#f7f8f8;padding:1rem}.direction-name{color:#008060;font-size:.85rem;font-weight:700}.subheading{font-size:.8rem;font-weight:600;color:#4a4f54}.tag{border-radius:999px;background:#e3f1df;padding:.35rem .65rem;color:#006e52;font-size:.8rem}.summary-text{margin-top:.4rem;color:#616161;font-size:.875rem}.insight{border:1px solid #e1e3e5;border-radius:.5rem;background:#f7f8f8;padding:1rem}.insight-good{border-color:#b7d9c8;background:#f1f8f5}.insight b{font-size:.875rem}.insight ul{margin-top:.6rem;display:grid;gap:.4rem;color:#4a4f54;font-size:.8rem}.insight li{padding-left:1rem;position:relative}.insight li:before{content:'•';left:0;position:absolute;color:#008060}.evidence-title{display:flex;align-items:center;gap:.45rem;margin-bottom:.55rem}.evidence-title b{margin:0}.number{display:inline-flex;height:1.5rem;width:1.5rem;flex:none;align-items:center;justify-content:center;border-radius:999px;background:#e3f1df;color:#006e52;font-size:.75rem;font-weight:700}.skill-gap{display:flex;align-items:center;justify-content:space-between;gap:1rem;border:1px solid #e1e3e5;border-radius:.5rem;background:#fff;padding:.8rem}.skill-gap b{font-size:.9rem}.skill-gap span{color:#008060;font-size:.8rem;font-weight:600;white-space:nowrap}
</style>
